In [2]:
# This is the first  of pandas library tutorial that i am presenting .
# Pandas is much more sophisticated library (dependency ) as compared to numpy
# Data structures in Pandas are:(Series , Data Frame , Panel )


In [14]:
# Series refers to 1-dimensional arrays in Pandas 
import pandas as pd
import numpy as np
import random 
s1=pd.Series(np.random.randn(5))# 'randn' gives the normal distribution of (-5,5)
print(s1)

0   -1.191999
1   -0.887544
2    0.876181
3   -0.022150
4    0.194570
dtype: float64


In [29]:
#Apart from series  we have data frames(dictionary , 2d array etc.
d = {'c1':[1,2,3,4,5,6],
    'c2':[2,3,4,5,6,7],'c3':[4,5,6,7,7,8]}
df = pd.DataFrame(d)
print(df)

   c1  c2  c3
0   1   2   4
1   2   3   5
2   3   4   6
3   4   5   7
4   5   6   7
5   6   7   8


In [33]:
# Then we have panel that handles 3d data 
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,2,3,4],[5,4,3,2]]])
print(d)# this is 3d array we have ie having (2 axis x 2 rows x 4 columns) 

[[[1 2 3 4]
  [5 6 7 8]]

 [[9 2 3 4]
  [5 4 3 2]]]


In [37]:
# Panels have been depreciated from Pandas library so  i am still not clear about this one .